---
version: '3'

services:
  web:
    build:
      context: frontend
    env_file:
      - variables.env
    ports:
      - 8000:80
    depends_on:
      - db
  app:
    image: leolol481/demo4640:latest
    env_file:
      - variables.env
    depends_on:
      - db
  db:
    image: mysql
    env_file:
      - variables.env
  db_insert:
    build:
      context: db_insert
    env_file:
      - variables.env
    depends_on:
      - app